[device]
name = "SamuraiSight"
dev_ip = "10.10.76.18"
server_ip = "10.10.76.2"
[cameras]
    [cameras.cam1]
    name = "cam1"
    dev_id = 0
    calibration = true
    matrix = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
    dist_coeffs = [0, 0, 0, 0, 0]
    lenx = 640
    leny = 480
    fps = 60
    format = "Mjpeg"
    [cameras.cam2]
    name = "cam2"
    dev_id = 1
    calibration = true
    matrix = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
    dist_coeffs = [0, 0, 0, 0, 0]
    lenx = 640
    leny = 480
    fps = 60
    format = "Mjpeg"
[pipelines]
    [pipelines.pipeline1]
    name = "pipeline1"
    camera = "cam1"
    type = "apriltag"
    stream = false
    rawport = 8000
    processedport = 8001
    [pipelines.pipeline2]
    name = "pipeline2"
    camera = "cam2"
    type = "apriltag"
    stream = true
    rawport = 8002
    processedport = 8003



